from S1E7 import Baratheon, Lannister

Robert = Baratheon("Robert")
print(Robert.__dict__)
print(Robert.is_alive)
Robert.die()
print(Robert.is_alive)
print(Robert.__doc__)
print("---")
Cersei = Lannister("Cersei")
print(Cersei.__dict__)
print(Cersei.__str__)
print(Cersei.__repr__)
print(Cersei.is_alive)
print(Cersei.__doc__)
print("---")
Tywin = Lannister.create_lannister("Tywin", True)
Tywin.die()
print(f"Name : {Tywin.first_name, type(Tywin).__name__}, Alive : {Tywin.is_alive}")